spring:
  datasource:
    jndi-name: umeDs
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.Oracle12cDialect
  data:
    rest:
      detection-strategy: annotated
  http:
    encoding:
      enabled: false